version: '3.7'
services:
  redis:
    image: redis:5-alpine
    volumes:
      - ../mounts/redisdata:/data
  watcher:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: redis
    depends_on:
      - redis