version: '3.7'
services:
  watcher-count-referenced-by:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: setup
    command: ["python", "./src/watch.py", "count-referenced-by"]
    depends_on:
      - postgres
      - redis