version: '3.7'
services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - ../mounts/pgdata:/var/lib/postgresql/data
  watcher:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: postgres
    depends_on:
      - postgres