version: '3.7'
services:
  blast:
    image: mosuka/blast:v0.3.2
    environment:
      BLAST_BIND_ADDR: blast:10000
      BLAST_GRPC_ADDR: blast:10001
      BLAST_HTTP_ADDR: blast:10002
      BLAST_RAFT_NODE_ID: node1
      BLAST_RAFT_DIR: /blastdata/node1/raft
      BLAST_STORE_DIR: /blastdata/node1/store
      BLAST_INDEX_DIR: /blastdata/node1/index
      BLAST_INDEX_MAPPING: /blastdata/index_mapping.json
    volumes:
      - ./mounts/blastdata:/blastdata
    command: start
  watcher:
    build:
      context: .
      target: blast
    depends_on:
      - blast